export const state = () => ({
  regions: [
    { diler: true, city: 'Абакан', address: 'Варшавское ш., д.1', left: 48, top: 198},
    { diler: true, city: 'Альметьевск', address: 'Варшавское ш., д.1', left: 48, top: 198},
    { diler: true, city: 'Альметьевск', address: 'Варшавское ш., д.1', left: 48, top: 198},
    { city: 'Ангарск', address: 'Варшавское ш., д.1', left: 48, top: 198},
    { diler: true, city: 'Архангельск', address: 'Варшавское ш., д.1', left: 48, top: 198},
    { city: 'Астрахань', address: 'Варшавское ш., д.1', left: 48, top: 198},
    { diler: true, city: 'Ачинск', address: 'Варшавское ш., д.1', left: 48, top: 198},
    { diler: true, city: 'Балаково', address: 'Варшавское ш., д.1', left: 48, top: 198},
    { city: 'Балашиха', address: 'Варшавское ш., д.1', left: 48, top: 198},
    { city: 'Барнаул', address: 'Варшавское ш., д.1', left: 48, top: 198},
    { city: 'Белгород', address: 'Варшавское ш., д.1', left: 48, top: 198},
    { city: 'Бийск', address: 'Варшавское ш., д.1', left: 48, top: 198},
    { city: 'Биробиджан', address: 'Варшавское ш., д.1', left: 48, top: 198},
    { diler: true, city: 'Благовещенск', address: 'Варшавское ш., д.1', left: 48, top: 198},
    { city: 'Братск', address: 'Варшавское ш., д.1', left: 48, top: 198},
    { city: 'Брянск', address: 'Варшавское ш., д.1', left: 48, top: 198},
    { city: 'Великие Луки', address: 'Варшавское ш., д.1', left: 48, top: 198},
    { diler: true, city: 'Великий Новгород', address: 'Варшавское ш., д.1', left: 48, top: 198},
    { diler: true, city: 'Владивосток', address: 'Варшавское ш., д.1', left: 48, top: 198},
    { diler: true, city: 'Владикавказ', address: 'Варшавское ш., д.1', left: 48, top: 198},
    { diler: true, city: 'Владимир', address: 'Варшавское ш., д.1', left: 48, top: 198},
    { diler: true, city: 'Волгоград', address: 'Варшавское ш., д.1', left: 48, top: 198},
    { diler: true, city: 'Волжский', address: 'Варшавское ш., д.1', left: 48, top: 198},
    { diler: true, city: 'Вологда', address: 'Варшавское ш., д.1', left: 48, top: 198},
    { diler: true, city: 'Воронеж', address: 'Варшавское ш., д.1', left: 48, top: 198},
    { diler: true, city: 'Глазов', address: 'Варшавское ш., д.1', left: 48, top: 198},
    { city: 'Горно-Алтайск', address: 'Варшавское ш., д.1', left: 48, top: 198},
    { city: 'Грозный', address: 'Варшавское ш., д.1', left: 48, top: 198},
    { city: 'Дзержинск', address: 'Варшавское ш., д.1', left: 48, top: 198},
    { diler: true, city: 'Екатеринбург', address: 'Варшавское ш., д.1', left: 48, top: 198},
    { city: 'Иваново', address: 'Варшавское ш., д.1', left: 48, top: 198},
    { diler: true, city: 'Ижевск', address: 'Варшавское ш., д.1', left: 48, top: 198},
    { diler: true, city: 'Иркутск', address: 'Варшавское ш., д.1', left: 48, top: 198},
    { city: 'Йошкар-Ола', address: 'Варшавское ш., д.1', left: 48, top: 198},
    { city: 'Казань', address: 'Варшавское ш., д.1', left: 48, top: 198},
    { diler: true, city: 'Калининград', address: 'Варшавское ш., д.1', left: 48, top: 198},
    { city: 'Калуга', address: 'Варшавское ш., д.1', left: 48, top: 198},
    { diler: true, city: 'Канск', address: 'Варшавское ш., д.1', left: 48, top: 198},
    { diler: true, city: 'Кемерово', address: 'Варшавское ш., д.1', left: 48, top: 198},
    { diler: true, city: 'Керчь', address: 'Варшавское ш., д.1', left: 48, top: 198},
    { city: 'Киров', address: 'Варшавское ш., д.1', left: 48, top: 198},
    { diler: true, city: 'Коломна', address: 'Варшавское ш., д.1', left: 48, top: 198},
    { diler: true, city: 'Комсомольск-на-Амуре', address: 'Варшавское ш., д.1', left: 48, top: 198},
    { city: 'Кострома', address: 'Варшавское ш., д.1', left: 48, top: 198},
    { diler: true, city: 'Краснодар', address: 'Варшавское ш., д.1', left: 48, top: 198},
    { diler: true, city: 'Красноярск', address: 'Варшавское ш., д.1', left: 48, top: 198},
    { city: 'Курган', address: 'Варшавское ш., д.1', left: 48, top: 198},
    { city: 'Курск', address: 'Варшавское ш., д.1', left: 48, top: 198},
    { diler: true, city: 'Кызыл', address: 'Варшавское ш., д.1', left: 48, top: 198},
    { diler: true, city: 'Кырен', address: 'Варшавское ш., д.1', left: 48, top: 198},
    { diler: true, city: 'Липецк', address: 'Варшавское ш., д.1', left: 48, top: 198},
    { diler: true, city: 'Магадан', address: 'Варшавское ш., д.1', left: 48, top: 198},
    { city: 'Магнитогорск', address: 'Варшавское ш., д.1', left: 48, top: 198},
    { city: 'Майкоп', address: 'Варшавское ш., д.1', left: 48, top: 198},
    { diler: true, city: 'Махачкала', address: 'Варшавское ш., д.1', left: 48, top: 198},
    { city: 'Миасс', address: 'Варшавское ш., д.1', left: 48, top: 198},
    { diler: true, city: 'Минусинск', address: 'Варшавское ш., д.1', left: 48, top: 198},
    { diler: true, city: 'Москва', address: 'Варшавское ш., д.11', left: 48, top: 198},
    { diler: true, city: 'Мурманск', address: 'Варшавское ш., д.1', left: 48, top: 198},
    { diler: true, city: 'Набережные Челны', address: 'Варшавское ш., д.1', left: 48, top: 198},
    { city: 'Назрань', address: 'Варшавское ш., д.1', left: 48, top: 198},
    { city: 'Нальчик', address: 'Варшавское ш., д.1', left: 48, top: 198},
    { diler: true, city: 'Находка', address: 'Варшавское ш., д.1', left: 48, top: 198},
    { city: 'Нерюнгри', address: 'Варшавское ш., д.1', left: 48, top: 198},
    { city: 'Нефтеюганск', address: 'Варшавское ш., д.1', left: 48, top: 198},
    { city: 'Нижневартовск', address: 'Варшавское ш., д.1', left: 48, top: 198},
    { city: 'Нижнекамск', address: 'Варшавское ш., д.1', left: 48, top: 198},
    { diler: true, city: 'Нижний Новгород', address: 'Варшавское ш., д.1', left: 48, top: 198},
    { city: 'Нижний Тагил', address: 'Варшавское ш., д.1', left: 48, top: 198},
    { diler: true, city: 'Новокузнецк', address: 'Варшавское ш., д.1', left: 48, top: 198},
    { diler: true, city: 'Новороссийск', address: 'Варшавское ш., д.1', left: 48, top: 198},
    { diler: true, city: 'Новосибирск', address: 'Варшавское ш., д.1', left: 48, top: 198},
    { city: 'Новочеркасск', address: 'Варшавское ш., д.1', left: 48, top: 198},
    { diler: true, city: 'Омск', address: 'Варшавское ш., д.1', left: 48, top: 198},
    { city: 'Орел', address: 'Варшавское ш., д.1', left: 48, top: 198},
    { diler: true, city: 'Оренбург', address: 'Варшавское ш., д.1', left: 48, top: 198},
    { city: 'Орск', address: 'Варшавское ш., д.1', left: 48, top: 198},
    { city: 'Пенза', address: 'Варшавское ш., д.1', left: 48, top: 198},
    { city: 'Первоуральск', address: 'Варшавское ш., д.1', left: 48, top: 198},
    { diler: true, city: 'Пермь', address: 'Варшавское ш., д.1', left: 48, top: 198},
    { diler: true, city: 'Петрозаводск', address: 'Варшавское ш., д.1', left: 48, top: 198},
    { diler: true, city: 'Петропавловск-Камчатский', address: 'Варшавское ш., д.1', left: 48, top: 198},
    { city: 'Прокопьевск', address: 'Варшавское ш., д.1', left: 48, top: 198},
    { diler: true, city: 'Псков', address: 'Варшавское ш., д.1', left: 48, top: 198},
    { diler: true, city: 'Пятигорск', address: 'Варшавское ш., д.1', left: 48, top: 198},
    { city: 'Россия', address: 'Варшавское ш., д.1', left: 48, top: 198},
    { diler: true, city: 'Ростов-на-Дону', address: 'Варшавское ш., д.1', left: 48, top: 198},
    { diler: true, city: 'Рыбинск', address: 'Варшавское ш., д.1', left: 48, top: 198},
    { city: 'Рязань', address: 'Варшавское ш., д.1', left: 48, top: 198},
    { city: 'Салават', address: 'Варшавское ш., д.1', left: 48, top: 198},
    { diler: true, city: 'Самара', address: 'Варшавское ш., д.1', left: 48, top: 198},
    { diler: true, city: 'Санкт-Петербург', address: 'Варшавское ш., д.1', left: 22, top: 148},
    { city: 'Саранск', address: 'Варшавское ш., д.1', left: 48, top: 198},
    { diler: true, city: 'Саратов', address: 'Варшавское ш., д.1', left: 48, top: 198},
    { city: 'Саяногорск', address: 'Варшавское ш., д.1', left: 48, top: 198},
    { diler: true, city: 'Севастополь', address: 'Варшавское ш., д.1', left: 48, top: 198},
    { diler: true, city: 'Симферополь', address: 'Варшавское ш., д.1', left: 48, top: 198},
    { diler: true, city: 'Смоленск', address: 'Варшавское ш., д.1', left: 48, top: 198},
    { diler: true, city: 'Сочи', address: 'Варшавское ш., д.1', left: 48, top: 198},
    { city: 'Ставрополь', address: 'Варшавское ш., д.1', left: 48, top: 198},
    { city: 'Старый Оскол', address: 'Варшавское ш., д.1', left: 48, top: 198},
    { diler: true, city: 'Стерлитамак', address: 'Варшавское ш., д.1', left: 48, top: 198},
    { city: 'Ступино', address: 'Варшавское ш., д.1', left: 48, top: 198},
    { diler: true, city: 'Сургут', address: 'Варшавское ш., д.1', left: 48, top: 198},
    { city: 'Сызрань', address: 'Варшавское ш., д.1', left: 48, top: 198},
    { city: 'Сыктывкар', address: 'Варшавское ш., д.1', left: 48, top: 198},
    { city: 'Таганрог', address: 'Варшавское ш., д.1', left: 48, top: 198},
    { city: 'Тамбов', address: 'Варшавское ш., д.1', left: 48, top: 198},
    { diler: true, city: 'Тверь', address: 'Варшавское ш., д.1', left: 48, top: 198},
    { city: 'Тобольск', address: 'Варшавское ш., д.1', left: 48, top: 198},
    { diler: true, city: 'Тольятти', address: 'Варшавское ш., д.1', left: 48, top: 198},
    { diler: true, city: 'Томск', address: 'Варшавское ш., д.1', left: 48, top: 198},
    { city: 'Тула', address: 'Варшавское ш., д.1', left: 48, top: 198},
    { diler: true, city: 'Тюмень', address: 'Варшавское ш., д.1', left: 48, top: 198},
    { diler: true, city: 'Улан-Удэ', address: 'Варшавское ш., д.1', left: 48, top: 198},
    { diler: true, city: 'Ульяновск', address: 'Варшавское ш., д.1', left: 48, top: 198},
    { diler: true, city: 'Уссурийск', address: 'Варшавское ш., д.1', left: 48, top: 198},
    { city: 'Усть-Илимск', address: 'Варшавское ш., д.1', left: 48, top: 198},
    { diler: true, city: 'Уфа', address: 'Варшавское ш., д.1', left: 48, top: 198},
    { diler: true, city: 'Хабаровск', address: 'Варшавское ш., д.1', left: 48, top: 198},
    { city: 'Чебоксары', address: 'Варшавское ш., д.1', left: 48, top: 198},
    { diler: true, city: 'Челябинск', address: 'Варшавское ш., д.1', left: 48, top: 198},
    { city: 'Череповец', address: 'Варшавское ш., д.1', left: 48, top: 198},
    { diler: true, city: 'Чита', address: 'Варшавское ш., д.1', left: 48, top: 198},
    { city: 'Шахты', address: 'Варшавское ш., д.1', left: 48, top: 198},
    { city: 'Элиста', address: 'Варшавское ш., д.1', left: 48, top: 198},
    { city: 'Энгельс', address: 'Варшавское ш., д.1', left: 48, top: 198},
    { diler: true, city: 'Южно-Сахалинск', address: 'Варшавское ш., д.1', left: 48, top: 198},
    { diler: true, city: 'Якутск', address: 'Варшавское ш., д.1', left: 48, top: 198},
    { diler: true, city: 'Ярославль', address: 'Варшавское ш., д.1', left: 48, top: 198},
  ]
})

export const getters = {
  getRegions: state => state.regions,
}

export const mutations = {}
export const actions = {}
